### ISSUE TITLE
Routes in UserServlet are not working

### ISSUE THREAD

**Issue by tayweilong** [tayweilong/DevopS#13]
dev branch, opened with xampp and apache server

![image](https://user-images.githubusercontent.com/97167032/150726470-6c13c3a2-0bcd-47d2-84a1-e0218b1ce9d2.png)

**Comment by tayweilong** [comment]
solved

**Comment by jyorien** [comment]
This issue is not related to the codebase. Check your XAMPP / phpmyadmin. There may be a wrong configuration.
