### ISSUE TITLE
Routes are not working inside UserServlet

### ISSUE THREAD

**Issue by tayweilong** [tayweilong/DevopS#16]
I  get a 404 error when I access /DevopS/UserServlet/, but  /DevopS/UserServlet/Dashboard seems to work.

Accessing  /DevopS/UserServlet/Dashboard
![image](https://user-images.githubusercontent.com/97167032/150733242-32f0cf5d-68b4-48dc-a6e3-74a15862a50b.png)

Accessing  /DevopS/UserServlet/
![image](https://user-images.githubusercontent.com/97167032/150733278-0e17bced-ccb4-4305-8eba-5c0e0310e322.png)

**Comment by jyorien** [comment]
This issue brings up the same problem as #20
