### ISSUE TITLE
add readme

### ISSUE THREAD

**Issue by wenhuibbb** [tayweilong/DevopS#18]
**Is your feature request related to a problem? Please describe.**
the problem theres no documentation for someone to know about this repository.

**Describe the solution you'd like**
It would be easier if theres some kind of description and guide for this problem 

**Describe alternatives you've considered**
 don't have any alternatives

**Additional context**
NIA

**Comment by wenhuibbb** [comment]
erferf

**Comment by hhafzahh** [comment]
Issue has been resolved.
