### ISSUE TITLE
Update user is not working

### ISSUE THREAD

**Issue by jyorien** [tayweilong/DevopS#24]
**Describe the bug**
When I click edit, it does not edit the user's details in the user dashboard

**To Reproduce**
1. Go to /UserServlet/dashboard
2. Click on 'Edit'
3. Edit the details
4. Click 'Save'
5. Go back to dashboard

**Expected behavior**
User details get updated in the dashboard

**Additional context**
The updateUser method is missing. I need the method to be implemented

**Comment by tayweilong** [comment]
Working on it.
